name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v4
    - name: Setup Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # tag=v5
      with:
        go-version: "1.26"
        check-latest: true
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # tag=v9.2.1
      with:
        version: latest

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # tag=v5
      with:
        go-version: "1.26"
        check-latest: true
    - name: Checkout Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v4
    - name: Test
      run: make test
